CREATE PROCEDURE [dbo].[spA_Claim_GetById]
    @claimID INT
AS

SELECT TOP 1
    [Claim].[ClaimID]
    , [Patient].[PatientID]
    , [Patient].[LastName]                    AS [PatientLastName]
    , [Patient].[FirstName]                   AS [PatientFirstName]
    , [Patient].[MiddleName]                  AS [PatientMiddleName]
    , [P_Address].[Street]                    AS [PatientStreet]
    , [P_City].[Name]                         AS [PatientCity]
    , [P_State].[Name]                        AS [PatientState]
    , [P_Zip].[Code]                          AS [PatientZip]
    , [P_PhoneNumber].[PhoneNumber]           AS [PatientPhoneNumber]
    , [P_EmailAddress].[EmailAddress]         AS [PatientEmailAddress]
    , [Carrier].[CarrierID]
    , [Carrier].[Name]                        AS [CarrierName]
    , [C_PhoneNumber].[PhoneNumber]           AS [CarrierCustomerServicePhoneNumber]
    , [Hospital].[HospitalID]
    , [Hospital].[Name]                       AS [HospitalName]
    , [H_Address].[Street]                    AS [HospitalStreet]
    , [H_City].[Name]                         AS [HospitalCity]
    , [H_State].[Name]                        AS [HospitalState]
    , [H_Zip].[Code]                          AS [HospitalZip]
    , [Procedure].[ProcedureID]
    , [Procedure].[Code]                      AS [ProcedureCode]
    , [Procedure].[Name]                      AS [ProcedureName]
    , [Claim].[OutstandingAmount]             AS [ClaimOutstandingAmount]
    , [Claim].[InsuranceResponsibilityAmount] AS [ClaimInsuranceResponsibilityAmount]
FROM
    [Claim]
    INNER JOIN [Patient]                          ON [Claim].[PatientID]                      = [Patient].[PatientID]
    INNER JOIN [Address]      AS [P_Address]      ON [Patient].[AddressID]                    = [P_Address].[AddressID]
    INNER JOIN [City]         AS [P_City]         ON [P_Address].[CityID]                     = [P_City].[CityID]
    INNER JOIN [State]        AS [P_State]        ON [P_City].[StateID]                       = [P_State].[StateID]
    INNER JOIN [Zip]          AS [P_Zip]          ON [P_Address].[ZipID]                      = [P_Zip].[ZipID]
    INNER JOIN [PhoneNumber]  AS [P_PhoneNumber]  ON [Patient].[PhoneNumberID]                = [P_PhoneNumber].[PhoneNumberID]
    INNER JOIN [EmailAddress] AS [P_EmailAddress] ON [Patient].[EmailAddressID]               = [P_EmailAddress].[EmailAddressID]
    INNER JOIN [Carrier]                          ON [Claim].[CarrierID]                      = [Carrier].[CarrierID]
    INNER JOIN [PhoneNumber]  AS [C_PhoneNumber]  ON [Carrier].[CustomerServicePhoneNumberID] = [C_PhoneNumber].[PhoneNumberID]
    INNER JOIN [Hospital]                         ON [Claim].[HospitalID]                     = [Hospital].[HospitalID]
    INNER JOIN [Address]      AS [H_Address]      ON [Hospital].[AddressID]                   = [H_Address].[AddressID]
    INNER JOIN [City]         AS [H_City]         ON [H_Address].[CityID]                     = [H_City].[CityID]
    INNER JOIN [State]        AS [H_State]        ON [H_City].[StateID]                       = [H_State].[StateID]
    INNER JOIN [Zip]          AS [H_Zip]          ON [H_Address].[ZipID]                      = [H_Zip].[ZipID]
    INNER JOIN [Procedure]                        ON [Claim].[ProcedureID]                    = [Procedure].[ProcedureID]
WHERE
    [Claim].[ClaimID] = @claimID
;
