CREATE PROCEDURE [dbo].[spA_Claim_GetById]
    @claimId INT
AS

SELECT TOP 1
      [Claim].[Id]                            AS [ClaimId]
    , [Patient].[Id]                          AS [PatientId]
    , [Patient].[LastName]                    AS [PatientLastName]
    , [Patient].[FirstName]                   AS [PatientFirstName]
    , [Patient].[MiddleName]                  AS [PatientMiddleName]
    , [P_Address].[Street]                    AS [PatientStreet]
    , [P_City].[Name]                         AS [PatientCity]
    , [P_State].[Name]                        AS [PatientState]
    , [P_Zip].[Code]                          AS [PatientZip]
    , [P_PhoneNumber].[PhoneNumber]           AS [PatientPhoneNumber]
    , [P_EmailAddress].[EmailAddress]         AS [PatientEmailAddress]
    , [Carrier].[Id]                          AS [CarrierId]
    , [Carrier].[Name]                        AS [CarrierName]
    , [C_PhoneNumber].[PhoneNumber]           AS [CarrierCustomerServicePhoneNumber]
    , [Hospital].[Id]                         AS [HospitalId]
    , [Hospital].[Name]                       AS [HospitalName]
    , [H_Address].[Street]                    AS [HospitalStreet]
    , [H_City].[Name]                         AS [HospitalCity]
    , [H_State].[Name]                        AS [HospitalState]
    , [H_Zip].[Code]                          AS [HospitalZip]
    , [Procedure].[Id]                        AS [ProcedureId]
    , [Procedure].[Code]                      AS [ProcedureCode]
    , [Procedure].[Name]                      AS [ProcedureName]
    , [Claim].[OutstandingAmount]             AS [ClaimOutstandingAmount]
    , [Claim].[InsuranceResponsibilityAmount] AS [ClaimInsuranceResponsibilityAmount]
FROM
               [Claim]
    INNER JOIN [Patient]                          ON [Claim].[PatientId]                      = [Patient].[Id]
    INNER JOIN [Address]      AS [P_Address]      ON [Patient].[AddressId]                    = [P_Address].[Id]
    INNER JOIN [City]         AS [P_City]         ON [P_Address].[CityId]                     = [P_City].[Id]
    INNER JOIN [State]        AS [P_State]        ON [P_City].[StateId]                       = [P_State].[Id]
    INNER JOIN [Zip]          AS [P_Zip]          ON [P_Address].[ZipId]                      = [P_Zip].[Id]
    INNER JOIN [PhoneNumber]  AS [P_PhoneNumber]  ON [Patient].[PhoneNumberId]                = [P_PhoneNumber].[Id]
    INNER JOIN [EmailAddress] AS [P_EmailAddress] ON [Patient].[EmailAddressId]               = [P_EmailAddress].[Id]
    INNER JOIN [Carrier]                          ON [Claim].[CarrierId]                      = [Carrier].[Id]
    INNER JOIN [PhoneNumber]  AS [C_PhoneNumber]  ON [Carrier].[CustomerServicePhoneNumberId] = [C_PhoneNumber].[Id]
    INNER JOIN [Hospital]                         ON [Claim].[HospitalId]                     = [Hospital].[Id]
    INNER JOIN [Address]      AS [H_Address]      ON [Hospital].[AddressId]                   = [H_Address].[Id]
    INNER JOIN [City]         AS [H_City]         ON [H_Address].[CityId]                     = [H_City].[Id]
    INNER JOIN [State]        AS [H_State]        ON [H_City].[StateId]                       = [H_State].[Id]
    INNER JOIN [Zip]          AS [H_Zip]          ON [H_Address].[ZipId]                      = [H_Zip].[Id]
    INNER JOIN [Procedure]                        ON [Claim].[ProcedureId]                    = [Procedure].[Id]
WHERE
    [Claim].[Id] = @claimId
;
